apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    name: nginx

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app:  nginx
    spec:
      containers:
      - image: nginx:1.17-alpine
        name: nginx

        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            cpu: "23m"
            memory: "55M"

        ports:
        - containerPort:  80

        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: nginx-index

      volumes:
      - name: nginx-index
        configMap:
          name: nginx-index
          items:
          - key: nginx-index
            path: index.html

